{% set name = "zenpy" %}
{% set version = "2.0.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zenpy-{{ version }}.tar.gz
  sha256: b10d2ce251a49a9a2671c196a4ba819cc59ac07c9b71024c0fc1d7a33fe8b49e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.14.2
    - python-dateutil >=2.7.5
    - cachetools >=3.1.0
    - pytz >=2018.9
    - six >=1.14.0

test:
  imports:
    - zenpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facetoe/zenpy
  summary: Python wrapper for the Zendesk API
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: http://docs.facetoe.com.au/
  dev_url: https://github.com/facetoe/zenpy

extra:
  recipe-maintainers:
    - xylar
