{% set name = "zenpy" %}
{% set version = "2.0.56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zenpy-{{ version }}.tar.gz
  sha256: 984cdcd93dde5d70fa0e2d5c1d1878b8700dc26df63ca3414f6b55577423cb1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.14.2
    - python-dateutil >=2.7.5
    - cachetools >=3.1.0
    - pytz >=2018.9
    - six >=1.14.0

test:
  imports:
    - zenpy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/facetoe/zenpy
  summary: Python wrapper for the Zendesk API
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: http://docs.facetoe.com.au/
  dev_url: https://github.com/facetoe/zenpy

extra:
  recipe-maintainers:
    - xylar
